#:schema node_modules/wrangler/config-schema.json
name = "vid-summarizer"
main = "src/index.js"
compatibility_date = "2024-08-21"
node_compat = true

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "TRANSCRIPTS"
id = "79006f91f76d434f819a3287fdedf800"